### ISSUE TITLE
jsonl2csv does not seem to handle .gz files

### ISSUE THREAD

**Issue by gm3dmo** [gm3dmo/syslog-to-csv#32]
```
--- Logging error ---
Traceback (most recent call last):
  File "syslog-to-csv/b2c.py", line 102, in main
    subprocess.run([cmd], check=True, shell=True)
  File "/usr/lib/pypy3.9/subprocess.py", line 528, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/bin/pypy3 syslog-to-csv/jsonl-to-csv.py github-logs/exceptions.log.5.gz --log-type exceptions --csv-file github-logs/exceptions.log.5.gz.csv']' returned non-zero exit status 1.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/pypy3.9/logging/__init__.py", line 1083, in emit
    msg = self.format(record)
  File "/usr/lib/pypy3.9/logging/__init__.py", line 927, in format
    return fmt.format(record)
  File "/usr/lib/pypy3.9/logging/__init__.py", line 663, in format
    record.message = record.getMessage()
  File "/usr/lib/pypy3.9/logging/__init__.py", line 367, in getMessage
    msg = msg % self.args

```

**Comment by gm3dmo** [comment]
Fixed
